import javax.swing.*;
import javax.swing.JOptionPane.*;
import java.awt.Toolkit;
import java.awt.image.*;
import java.awt.datatransfer.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.geom.Ellipse2D;
import java.io.*;
import java.util.*;

public class req
{ 
    public static final String[] stuff=
    {
        "Must have at least 20 characters minimum.",
        "Must include a space.",
        "Needs to contain a fruit, but spelled backward.",
        "Your password must reference an animal that's commonly kept as a pet.",
        "Should have a type of bread embedded in it.",
        "Must include a Capital letter.",
        "Must contain the name of a primary color.",
        "Password should reference a common household appliance.",
        "Must have an even number of letters.",
        "Password should start with a consonant and end with a vowel.",
        "Must mention any footwear.",
        "Include the name of a thing that typically comes in pairs.",
        "Password must contain the word of a human organ.",
        "Must include a number divisible by 2.",
        "Password should include a two digit square number.",
        "Needs to have a single-digit prime number.",
        "Must contain an arithmetic operator.",
        "Password should include a common fraction.",
        "Must include an even number greater than 10.",
        "Must contain at least random number vowel",
        "Must include at least one of these punctuation marks.",
        "Must start with a consonant.",
        "Password must include the name of any mainstream female pop artist.",
        "Must contain a type of pasta.",
        "Needs to include the name of a berry.",
        "The password should contain three ascending alphabetical letters in a row.",
        "Include a type of cloud.",
        "Password must reference a common kitchen spice.",
        "Must hint at a popular recreational sport.",
        "Should have a word related to a dessert.",
        "Your password needs to have a name of a season.",
        "Should hint at a classical music composer.",
        "Must reference a body of water (e.g., river, lake, pond).",
        "Must contain a color and its opposite from the color wheel.",
        "Include the name of a body of land",
        "Password contains a Phillipine Volcano.",
        "Should incorporate a Phillipine Island.",
        "Include a country.",
        "Password must include the square root symbol.",
        "Should contain a randomly generated algebraic equation.",
        "Must reference a well-known mathematical constant.",
        "Password should have a factor of 12.",
        "Must include a mathematical term with three or more consecutive numbers.",
        "Should hint at the first five digits of a famous irrational number.",
        "Must have an even number of characters.",
        "Should contain both a lowercase and an uppercase English letter.",
        "Must include at least two of these symbols: !, @, #, $.",
        "Password must worth 8000 unicode amount.",
        "Password must inlclude a 1000 unicode amount character.",
        "Must reference the last letter of the world's largest ocean.",
        "Should contain the name of a dish typically eaten for breakfast.",
        "Password should hint at a famous dish from Italy, but not pizza.",
        "The password should be formatted as a postal address (e.g., 1234 Elm St).",
        "Your password needs a nod to a famous fictional detective.",
        "Must include a character that's not in the English alphabet.",
        "Password should allude to a famous historical event.",
        "Must contain a word from the title of a Shakespearean play.",
        "Your password needs to have a nod to a natural phenomenon.",
        "Should contain the name of a geometric shape.",
        "Needs to have a hint to a famous scientist.",
        "Must include the name of a gemstone.",
        "Must contain a reference to a prime number greater than 20.",
        "Password should include a mathematical series.",
        "Must have an expression related to complex numbers.",
        "Should include an integral or derivative symbol.",
        "Password must reference a concept from linear algebra.",
        "Must include an inequality statement.",
        "Cannot start with an English letter.",
        "Must have a palindrome sequence of at least 3 characters (like aba or 121).",
        "Password should include a ? or ! but not both.",
        "Cannot contain more than two vowels in sequence.",
        "Password ends with a four-digit number where the first two digits are the number of vowels and the last two digits are the number of consonants in the password.",
        "Must contain a basic equation using regex.",
        "Your password should reference a spicy cuisine.",
        "Must include a character from an old typewriter not present on modern keyboards.",
        "Must contain Binet's Fibonacci Formula.",
        "Should start with a vowel and end with a consonant.",
        "Must hint at a renowned artwork or artist.",
        "Password should contain a word related to ancient mythology.",
        "Should have a word in a language other than English, French, Spanish, or German.",
        "Must contain the name of a planet, but not Earth or Mars.",
        "Needs to reference a famous novel's title, but without its vowels.",
        "Password should have an allusion to a famous architect.",
        "Must have the names of a famous pop star in pop culture.",
        "Name a number in the billboard hot 100 one hit around 2020-2023",
        "Include the title of a blockbuster movie from the 2000s and its lead actor.",
        "Should mention a viral internet trend from 2018.",
        "Password must reference a major sporting event and its 2019 winner.",
        "Include a famous TV series from the 90s and its fictional setting.",
        "Password should reference a well-known mathematical theorem or conjecture.",
        "Must include a reference to a famous mathematician or mathematical concept.",
        "Should contain an equation involving a transcendental function.",
        "Password must hint at a principle from calculus (e.g., Mean Value Theorem).",
        "Must reference a term related to higher-level mathematics (e.g., homomorphism, manifold).",
        "Should include a symbolic representation of a complex geometric shape.",
        "Must include at least one Greek letter",
        "Should have a character sequence that forms a common abbreviation",
        "Requires at least two unicode punctuation marks (e.g., en dash ?, U+2013).",
        "Must start with an uppercase letter but not end with one.",
        "Should contain a combination of a letter, a number, a special character, and a space in sequence (like a1@ ).",
        "Must contain the first names of three female pop artists but backward.",
        "Must contain ten consecutive digits of the first 100 digits of pi.",
        "The password should be formatted as a potential web URL.",
        "Must include a type of chocolate (dark, white, milk...), but with all vowels removed.",
        "Should hint at a popular board game, but spelled in reverse.",
        "Must be formatted as a potential equation for Force (using regex).",
        "Include a hobby that gained popularity during quarantine, but with alternating letters capitalized.",
        "Password must contain a term from astrophysics.",
        "Should reference a concept from quantum mechanics.",
        "Must hint at a renowned mathematical theorem.",
        "Password should allude to a cultural tradition from Southeast Asia.",
        "Should contain the name of an indigenous tribe.",
        "Must reference an element from the periodic table, but in reverse.",
        "Must contain an equation involving differential equations.",
        "Password should allude to a concept from abstract algebra.",
        "Must reference a famous unsolved mathematical problem.",
        "Should include a reference to a concept from topology or number theory.",
        "Password must include a series expansion.",
        "Must hint at a famous open problem in mathematics.",
        "Requires a non-Latin script character.",
        "Password needs to include a rare special character.",
        "Must have a musical unicode symbol.",
        "Requires a three-character palindrome sequence.",
        "Password must not be 1/3 in CAPITAL LETTERS.",
        "Must contain a formula for Force or a recognized scientific formula.",
        "Password should reference a song from the '80s but in a language other than English.",
        "Should reference a meme from 2019, but in Morse code.",
        "Must include a sequence that looks random but is a famous encryption cipher's output.",
        "Needs a reference to a Taylor Swift song, but from her Red album, and converted into a series of numbers based on the alphabetical position of each letter.",
        "Must be a combination of three different prompts from previous levels, combined.",
        "Password must allude to a complex philosophical concept.",
        "Should contain a word that describes an obscure emotion.",
        "Must reference a term from neurobiology.",
        "Needs to hint at a linguistic phenomenon.",
        "Password should reference a rare meteorological event.",
        "Must contain a term from classical antiquity.",
        "Mention a planet in our solar system and one of its moons.",
        "Password must weave in a physical constant and its symbol.",
        "Reference a biological kingdom in it's scientific name.",
        "Include the name of a famous theorem in science.",
        "Password should reference a concept from advanced theoretical mathematics (e.g., group theory, category theory).",
        "Must contain a representation of a higher-dimensional geometric object.",
        "Should include a term related to advanced mathematical logic.",
        "Password must reference a deep mathematical concept or theorem beyond the undergraduate level.",
        "Must allude to a famous conjecture or problem in a specialized mathematical field.",
        "Should include a representation of a complex mathematical formula that would challenge even professional mathematicians.",
        "Must incorporate a character from a non-standard keyboard layout.",
        "Must begin and end with a unicode arrow character.",
        "Should include the name of a primary color but replace vowels with digits.",
        "Requires both an opening and closing character from this set.",
        "Should contain a sequence where letters are in alphabetical order.",
        "The Whole password must be a palindrome.",
        "Must include the unique BSIT-BTM Surnames"
    };
    
    public static void main(String[] args)
    {
        // some stuff here
    }
}
